name: Lab 4 CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      #Checkout repo
      - uses: actions/checkout@v3

      #Install node
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"
      
      #Install npm deps
      - name: Install dependencies
        run: npm clean-install
      
      #Run our linter
      - name: Run linter
        run: npm run lint